version: "0.1"

services:

  postgres:
    image: postgres:14.2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Postgresql14
    ports:
      - "5432:5432"
    volumes:
      - "db:/var/lib/postgresql/data"
    networks:
      - db

volumes:
  db:

networks:
  db:
